### PR TITLE
Fix unnecessary rendering of FastField

### LINKED ISSUE #1974: Performance issues in v2
### Current Behavior
Changes to any field (both Field and FastField) causes all fields in the form to re-render twice.

### Expected behavior

Changes to fields should only cause fields to re-render once, and more over, FastField should only re-render when changes are made to that field specifically.

### Reproducible example
Here's the same scenario demonstrated in both v2 and v1
v2.0.3 https://codesandbox.io/s/vigorous-wood-esy70
v1.5.8 https://codesandbox.io/s/keen-bouman-sx5r0

### Additional context
According to the react dev tools, the extra renders happen because "Context changed".

Possibly same problem as reported on #1759

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3
| React            | 16.8.4
| TypeScript       | 3.6.2
| Browser          | Chrome
| npm/Yarn         | yarn
| Operating System | windows

### PR DESCRIPTION
**Pull request by mvestergaard**
Whenever Context changes, shouldComponentUpdate is not called, which caused FastField to always re-render whenever Context changes
This adds a wrapper around FastField that grabs the Context, and passes it down as props

Fixes #1974, #2042, #1759

May depend on #2069 to be entirely fixed

### CODE REVIEW

**Comment by mvestergaard** [comment]
I tried my best to write a test that reproduces the problem, but it's really difficult, if not impossible in a "fake context".
Use the FastField story in the formik storybook to compare the behavior to before.

File: src/FastField.tsx [hunk 1]
```diff
@@ -36,12 +36,27 @@ export type FastFieldAttributes<T> = GenericFieldHTMLAttributes &
  * Custom Field component for quickly hooking into Formik
  * context and wiring up forms.
  */
-export class FastField<Values = {}, Props = {}> extends React.Component<
-  FastFieldAttributes<Props>,
+export function FastField<Values = {}, Props = {}>(
```
Comment (jaredpalmer) [inline src/FastField.tsx]: Can you just use connect()?

Comment (mvestergaard) [reply src/FastField.tsx]: I tried, but typescript and HOC's don't play well, can spend time trying to make it work if you insist.

Comment (mvestergaard) [reply src/FastField.tsx]: Just tried looking at it again. I can't figure out a way to use connect() and still preserve the generic arguments.

Comment (mvestergaard) [reply src/FastField.tsx]: I changed it to use connect() the same way as prior to 2.0, but this approach kind of makes it pointless for FastFieldInner to have generic arguments in the first place.

Your call.

**Comment by mvestergaard** [comment]
@jaredpalmer Can you take another look at this please? And possibly publish a new release including this and #2069 
Large forms are presently close to unusable

**Comment by jaredpalmer** [comment]
Publishing meow

**Comment by mhaylock** [comment]
@jaredpalmer what is the status of that release?

I went to look for the release attached to your comment above but I see the last release was 2.0.6, 17 days ago.
